/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvergenciasRouteImport } from './routes/convergencias'
import { Route as AlaRealmRouteImport } from './routes/ala.$realm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvergenciasRoute = ConvergenciasRouteImport.update({
  id: '/convergencias',
  path: '/convergencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AlaRealmRoute = AlaRealmRouteImport.update({
  id: '/ala/$realm',
  path: '/ala/$realm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convergencias': typeof ConvergenciasRoute
  '/ala/$realm': typeof AlaRealmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convergencias': typeof ConvergenciasRoute
  '/ala/$realm': typeof AlaRealmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convergencias': typeof ConvergenciasRoute
  '/ala/$realm': typeof AlaRealmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convergencias' | '/ala/$realm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convergencias' | '/ala/$realm'
  id: '__root__' | '/' | '/convergencias' | '/ala/$realm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvergenciasRoute: typeof ConvergenciasRoute
  AlaRealmRoute: typeof AlaRealmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convergencias': {
      id: '/convergencias'
      path: '/convergencias'
      fullPath: '/convergencias'
      preLoaderRoute: typeof ConvergenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ala/$realm': {
      id: '/ala/$realm'
      path: '/ala/$realm'
      fullPath: '/ala/$realm'
      preLoaderRoute: typeof AlaRealmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvergenciasRoute: ConvergenciasRoute,
  AlaRealmRoute: AlaRealmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
